name: Publish PWA to Github Pages

on:
  workflow_dispatch:

jobs:
  Build:
    name: Publish PWA to Github Pages
    runs-on: ubuntu-latest
    steps:

      - name: 📦 Checkout project repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + PNPM + install deps
        uses: ./.github/actions/setup-node-pnpm-install

      - name: ⚙️ Run Prebuild
        run: bun export
        shell: bash

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
